default: &default
  adapter: postgresql
  encoding: unicode
  host: <%= ENV["POSTGRES_HOST"] %>
  username: <%= ENV["POSTGRES_USER"] %>
  password: <%= ENV["POSTGRES_PASSWORD"] %>
  pool: 5

development:
  <<: *default
  database: nfc_app_dev


test:
  <<: *default
  database: nfc_app_test

production:
  <<: *default
  database: nfc_app_prod